### ISSUE TITLE
Attempt to open terminal for running container fails

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-linuxtools/org.eclipse.linuxtools#182]
### Environment
Windows 10
Open JDK 17.0.4
Running from sources: CDT (main) + Linux Tools (master)

### Steps to reproduce
* Run container
* Select "Execute Shell"
* Start typing command
=> Exception in the log, typed command is not visible
```
!ENTRY org.eclipse.linuxtools.docker.core 4 0 2023-05-11 18:16:07.841
!MESSAGE Unable to make field protected volatile java.io.InputStream java.io.FilterInputStream.in accessible: module java.base does not "opens java.io" to unnamed module @4f90225
!STACK 0
java.lang.reflect.InaccessibleObjectException: Unable to make field protected volatile java.io.InputStream java.io.FilterInputStream.in accessible: module java.base does not "opens java.io" to unnamed module @4f90225
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.eclipse.linuxtools.internal.docker.core.HttpHijackWorkaround.getInternalField(HttpHijackWorkaround.java:161)
	at org.eclipse.linuxtools.internal.docker.core.HttpHijackWorkaround.getOutputStream(HttpHijackWorkaround.java:116)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.openTerminal(DockerConnection.java:2350)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.execShell(DockerConnection.java:2318)
	at org.eclipse.linuxtools.internal.docker.ui.commands.ExecContainerCommandHandler.executeInJob(ExecContainerCommandHandler.java:39)
	at org.eclipse.linuxtools.internal.docker.ui.commands.BaseContainersCommandHandler$1.run(BaseContainersCommandHandler.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ruspl-afed** [comment]
I found a workaround that unlocked me
`--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED`

**Comment by ruspl-afed** [comment]
Yes, thank you @jjohnstn, your note confirmed [that I'm on the right way](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/issues/182#issuecomment-1544252118) to configure it for development environment. I will add two more `--add-opens` to match the p2 magic from your reply above. 

Please feel free to close this issue, since running from sources is a bit special case.

**Comment by jjohnstn** [comment]
Great.  Closing.
