### ISSUE TITLE
Docker Tooliing failing on Docker 4.27 for Apple Silicon

### ISSUE THREAD

**Issue by tcwan** [eclipse-linuxtools/org.eclipse.linuxtools#309]
Sonoma 14.3, Eclipse 2024-3, Docker for Mac 4.27, on M2 Mini. All software are Aarch64 native.

Docker tooling was working on previous version of Eclipse (2023-9) for this system with previous versions of Sonoma and Docker. 

However, after I upgraded macOS, Docker and Eclipse to the latest version (2024-3 for Aarch64), Docker Explorer ~fails to connect to~ encounters an error when accessing the Docker socket with the following error:

`An internal error occurred during: "Opening connection 'unix:///var/run/docker.sock'[unix:///var/run/docker.sock]...".
Cannot invoke "String.startsWith(String)" because "s" is null
`

/var/run/docker.sock is linked to the macOS user specific socket. I can check docker images via terminal as usual using 'docker images'

_Originally posted by @tcwan in https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/issues/61#issuecomment-1920389030_
            

Edit: Retitled issue, I think it has to do with new version of Sonoma as I tried with a reinstalled Eclipse 2023-9 and it didn't work either.
Edit2: Retitled to indicate issue with Docker 4.27. I found out that the error with docker.sock affects listing of images, whereas containers can be listed despite the error.

**Comment by akurtakov** [comment]
This would need to be investigated by someone with access(and some knowledge ) to MacOS (even a specific version). It would be best if you can look yourself in logs, debug, etc. to find out where this  'String.startsWith(String)" because "s" is null ' comes from.

**Comment by akurtakov** [comment]
Do you have any more details in Error log (https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-error_log_view.htm)  or the log file itself ?

**Comment by tcwan** [comment]
eclipse.buildId=4.31.0.20240111-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_MY
Framework arguments:  -product org.eclipse.epp.package.embedcpp.product -keyring /Users/tcmac/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.embedcpp.product -keyring /Users/tcmac/.eclipse_keyring

org.eclipse.launchbar.core
Error
Thu Feb 01 10:22:35 MYT 2024
Cannot invoke "String.startsWith(String)" because "s" is null

java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "s" is null
	at org.eclipse.linuxtools.docker.core.DockerException.calculateMessage(DockerException.java:56)
	at org.eclipse.linuxtools.docker.core.DockerException.<init>(DockerException.java:33)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.listImages(DockerConnection.java:1136)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1070)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.setState(DockerConnection.java:349)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.ping(DockerConnection.java:388)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.open(DockerConnection.java:292)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1062)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1032)
	at org.eclipse.cdt.docker.launcher.ContainerTargetTypeProvider.init(ContainerTargetTypeProvider.java:85)
	at org.eclipse.launchbar.core.internal.target.LaunchTargetManager.initTargets(LaunchTargetManager.java:123)
	at org.eclipse.launchbar.core.internal.target.LaunchTargetManager.getLaunchTarget(LaunchTargetManager.java:181)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.syncActiveTarget(LaunchBarManager.java:546)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.setActiveLaunchDescriptor(LaunchBarManager.java:502)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.addDescriptor(LaunchBarManager.java:313)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchObjectAdded(LaunchBarManager.java:362)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchConfigurationAdded(LaunchBarManager.java:916)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.init(LaunchBarManager.java:135)
	at org.eclipse.launchbar.core.internal.LaunchBarManager$1.run(LaunchBarManager.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by akurtakov** [comment]
Please update Docker tooling from https://download.eclipse.org/linuxtools/updates-docker-nightly/ . The latest build there should help us at least see a more reasonable exception as I doubt it would really fix the issue.

**Comment by tcwan** [comment]
I've selected only "Docker Tooling" from the list for the install/upgrade, though Docker Client Dependencies list various Apache and Jackson modules as being available for installation. I'm not sure if Eclipse automatically resolved these dependencies or if not installing them contributed to the errors shown below.

```
eclipse.buildId=4.31.0.20240111-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_MY
Framework arguments:  -product org.eclipse.epp.package.embedcpp.product -product org.eclipse.epp.package.embedcpp.product -keyring /Users/tcmac/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.embedcpp.product -data file:/Users/tcmac/eclipse-workspace/ -product org.eclipse.epp.package.embedcpp.product -keyring /Users/tcmac/.eclipse_keyring

org.eclipse.linuxtools.docker.core
Error
Fri Feb 02 07:11:05 MYT 2024
org.mandas.docker.client.exceptions.DockerRequestException: Request error: GET unix://localhost:80/images/json?all=true: 200

org.eclipse.linuxtools.docker.core.DockerException: org.mandas.docker.client.exceptions.DockerRequestException: Request error: GET unix://localhost:80/images/json?all=true: 200
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.listImages(DockerConnection.java:1136)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1070)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.setState(DockerConnection.java:349)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.ping(DockerConnection.java:388)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.open(DockerConnection.java:292)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1062)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1032)
	at org.eclipse.cdt.docker.launcher.ContainerTargetTypeProvider.init(ContainerTargetTypeProvider.java:85)
	at org.eclipse.launchbar.core.internal.target.LaunchTargetManager.initTargets(LaunchTargetManager.java:123)
	at org.eclipse.launchbar.core.internal.target.LaunchTargetManager.getLaunchTarget(LaunchTargetManager.java:181)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.syncActiveTarget(LaunchBarManager.java:546)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.setActiveLaunchDescriptor(LaunchBarManager.java:502)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.addDescriptor(LaunchBarManager.java:313)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchObjectAdded(LaunchBarManager.java:362)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchConfigurationAdded(LaunchBarManager.java:916)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.init(LaunchBarManager.java:135)
	at org.eclipse.launchbar.core.internal.LaunchBarManager$1.run(LaunchBarManager.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.mandas.docker.client.exceptions.DockerRequestException: Request error: GET unix://localhost:80/images/json?all=true: 200
	at org.mandas.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2589)
	at org.mandas.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2458)
	at org.mandas.docker.client.DefaultDockerClient.listImages(DefaultDockerClient.java:505)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.listImages(DockerConnection.java:1102)
	... 17 more
Caused by: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.mandas.docker.client.messages.ImmutableImage$Builder`, problem: Cannot build Image, some of required attributes are not set [virtualSize]
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 310] (through reference chain: java.util.ArrayList[0])
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:786)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)
	at org.mandas.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2456)
	... 19 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.mandas.docker.client.messages.ImmutableImage$Builder`, problem: Cannot build Image, some of required attributes are not set [virtualSize]
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 310] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1426)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1982)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:202)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2099)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1249)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:829)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:919)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:879)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:782)
	... 30 more
Caused by: java.lang.IllegalStateException: Cannot build Image, some of required attributes are not set [virtualSize]
	at org.mandas.docker.client.messages.ImmutableImage$Builder.build(ImmutableImage.java:746)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:200)
	... 46 more

```

**Comment by akurtakov** [comment]
Unfortunately, this is as far as I can help without MacOS to actually debug things. Now, I have to defer to someone with MacOS access or to actually debug/investigate.
It's quite likely that updating to latest https://mvnrepository.com/artifact/org.mandas/docker-client might be needed.
@jjohnstn What do you think?

**Comment by jjohnstn** [comment]
According to the last message, there is a problem with the virtualSize field.  According to the latest Docker API:

The VirtualSize field in the GET /images/{name}/json, GET /images/json, and GET /system/df responses is now omitted. Use the Size field instead, which contains the same information.

Looking at dmandalidiis github site, I see a virtualSize fix four days ago for ImageInfo so getting the latest and/or next version of docker-client might fix this.

**Comment by akurtakov** [comment]
Please try installing from https://download.eclipse.org/linuxtools/updates-docker-nightly/ and let us know of the result. We are interested in any positive or negative result so there is some time for fixes for the March release. Note that there RC1 build should be next Wed so it's a very tight schedule which is entirely dependent on people with Mac/Windows access to test.

**Comment by tcwan** [comment]
I had to install/upgrade "Docker Client Dependencies" in addition to the "Linux Docker Tooling" package. 

After doing so, I can access both containers and images as was the case previously (before Docker 4.27).

**Comment by akurtakov** [comment]
Thanks for verifying!
