### ISSUE TITLE
java.lang.NoClassDefFoundError error when running maven build

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-linuxtools/org.eclipse.linuxtools#322]
The maven build for Linuxtools has an exception after success, see full log [here](https://ci.eclipse.org/linuxtools/job/linuxtools/job/master/318/consoleText)

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:12 min
[INFO] Finished at: 2024-02-21T14:53:05-05:00
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:85)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText
	... 2 more
```

**Comment by akurtakov** [comment]
This is actual jgit issue as explained in https://github.com/eclipse-tycho/tycho/issues/3489 which no one found the time to report to jgit so far. Closing as it's nog linuxtools issue.
