### ISSUE TITLE
Docker Tools no longer works with the latest Eclipse version

### ISSUE THREAD

**Issue by elmuerte** [eclipse-linuxtools/org.eclipse.linuxtools#362]
Oomph recently updated to use a newer bcprov dependency (1.78.1). As a result the org.mandas.docker-client bundle required for the docker tools will no longer start.

```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.linuxtools.docker.core [4158]
  Unresolved requirement: Require-Bundle: org.mandas.docker-client; bundle-version="7.0.7"
    -> Bundle-SymbolicName: org.mandas.docker-client; bundle-version="7.0.7"
       org.mandas.docker-client [4172]
         Unresolved requirement: Import-Package: com.fasterxml.jackson.jakarta.rs.json; version="[2.16.0,3.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: com.google.auth.oauth2; resolution:="optional"
         Unresolved requirement: Import-Package: org.jboss.resteasy.client.jaxrs; resolution:="optional"
         Unresolved requirement: Import-Package: org.jboss.resteasy.client.jaxrs.engines; resolution:="optional"
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.mandas.docker-client [osgi.identity; type="osgi.bundle"; version:Version="7.0.7"; osgi.identity="org.mandas.docker-client"] because it is exposed to package 'org.bouncycastle.asn1.pkcs' from resources bcprov [osgi.identity; type="osgi.bundle"; version:Version="1.78.1"; osgi.identity="bcprov"] and org.bouncycastle.bcprov [osgi.identity; type="osgi.bundle"; version:Version="1.72.0.v20221013-1810"; osgi.identity="org.bouncycastle.bcprov"] via two dependency chains.

Chain 1:
  org.mandas.docker-client [osgi.identity; type="osgi.bundle"; version:Version="7.0.7"; osgi.identity="org.mandas.docker-client"]
    import: (&(osgi.wiring.package=org.bouncycastle.asn1.pkcs)(&(version>=1.77.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package: org.bouncycastle.asn1.pkcs
  bcprov [osgi.identity; type="osgi.bundle"; version:Version="1.78.1"; osgi.identity="bcprov"]

Chain 2:
  org.mandas.docker-client [osgi.identity; type="osgi.bundle"; version:Version="7.0.7"; osgi.identity="org.mandas.docker-client"]
    import: (&(osgi.wiring.package=org.bouncycastle.openssl)(&(version>=1.77.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=org.bouncycastle.openssl; uses:=org.bouncycastle.asn1.pkcs
  bcpkix [osgi.identity; type="osgi.bundle"; version:Version="1.77.0"; osgi.identity="bcpkix"]
    import: (&(osgi.wiring.package=org.bouncycastle.asn1.pkcs)(version>=1.72.0))
     |
    export: osgi.wiring.package: org.bouncycastle.asn1.pkcs
  org.bouncycastle.bcprov [osgi.identity; type="osgi.bundle"; version:Version="1.72.0.v20221013-1810"; osgi.identity="org.bouncycastle.bcprov"]
	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2004)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

**Comment by akurtakov** [comment]
Would you please try the soon to be released new version from https://download.eclipse.org/linuxtools/updates-docker-nightly/ ?

**Comment by elmuerte** [comment]
Had to update my Eclipse JRE to 21, but the nightly (5.16.0.202405281751) appears to work

**Comment by akurtakov** [comment]
Closing as per previous comment.
