### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown while parsing devhelp2 files

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [eclipse-linuxtools/org.eclipse.linuxtools#41]
Launching [Eclipse IDE for C/C++ Developers](https://www.eclipse.org/downloads/packages/release/2022-03/r/eclipse-ide-cc-developers) on my Gentoo system gives the following dialog:

![image](https://user-images.githubusercontent.com/50025045/163569279-e67d40e9-0712-4024-b1c6-f8ca2ed07e25.png)

And this entry in the workspace log file:
```
!ENTRY org.eclipse.core.jobs 4 2 2022-04-15 13:46:36.328
!MESSAGE An internal error occurred during: "Generating Library Hover help for installed devhelp documentation".
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.eclipse.linuxtools.internal.cdt.libhover.devhelp.ParseDevHelp$DevHelpParser.parse(ParseDevHelp.java:505)
        at org.eclipse.linuxtools.internal.cdt.libhover.devhelp.ParseDevHelp$DevHelpParser.parse(ParseDevHelp.java:383)
        at org.eclipse.linuxtools.internal.cdt.libhover.devhelp.DevHelpStartup$DevhelpStartupJob.run(DevHelpStartup.java:99)
```

With some minor debugging to narrowing down the issue points to that it's this XML content that causes the error:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns="http://www.devhelp.net/book" title="PangoFT2-1.0 Reference Manual" link="index.html" author="Owen Taylor, Behdad Esfahbod" name="PangoFT2" version="2" language="c">
   <chapters>
      <sub name="Classes Hierarchy" link="classes_hierarchy.html" />
      <sub name="Callbacks" link="index.html#callbacks">
         <sub name="SubstituteFunc" link="callback.SubstituteFunc.html" />
      </sub>
      <sub name="Classes" link="index.html#classes">
         <sub name="FontMap" link="class.FontMap.html" />
      </sub>
      <sub name="Functions" link="index.html#functions">
         <sub name="font_get_coverage" link="func.font_get_coverage.html" />
         <sub name="font_get_face" link="func.font_get_face.html" />
         <sub name="font_get_kerning" link="func.font_get_kerning.html" />
         <sub name="get_context" link="func.get_context.html" />
         <sub name="get_unknown_glyph" link="func.get_unknown_glyph.html" />
         <sub name="render" link="func.render.html" />
         <sub name="render_layout" link="func.render_layout.html" />
         <sub name="render_layout_line" link="func.render_layout_line.html" />
         <sub name="render_layout_line_subpixel" link="func.render_layout_line_subpixel.html" />
         <sub name="render_layout_subpixel" link="func.render_layout_subpixel.html" />
         <sub name="render_transformed" link="func.render_transformed.html" />
         <sub name="shutdown_display" link="func.shutdown_display.html" />
      </sub>
   </chapters>
   <functions>
      <keyword type="struct" name="PangoFT2FontMap" link="class.FontMap.html" />
      <keyword type="function" name="pango_ft2_font_map_create_context" link="method.FontMap.create_context.html" since="1.2" deprecated="1.22" />
      <keyword type="function" name="pango_ft2_font_map_set_default_substitute" link="method.FontMap.set_default_substitute.html" since="1.2" deprecated="1.46" />
      <keyword type="function" name="pango_ft2_font_map_set_resolution" link="method.FontMap.set_resolution.html" since="1.2" />
      <keyword type="function" name="pango_ft2_font_map_substitute_changed" link="method.FontMap.substitute_changed.html" since="1.2" deprecated="1.46" />
      <keyword type="function" name="pango_ft2_font_map_new" link="ctor.FontMap.new.html" since="1.2" />
      <keyword type="function" name="pango_ft2_font_map_for_display" link="type_func.FontMap.for_display.html" />
      <keyword type="function" name="pango_ft2_font_get_coverage" link="func.font_get_coverage.html" />
      <keyword type="function" name="pango_ft2_font_get_face" link="func.font_get_face.html" />
      <keyword type="function" name="pango_ft2_font_get_kerning" link="func.font_get_kerning.html" />
      <keyword type="function" name="pango_ft2_get_context" link="func.get_context.html" deprecated="1.22" />
      <keyword type="function" name="pango_ft2_get_unknown_glyph" link="func.get_unknown_glyph.html" />
      <keyword type="function" name="pango_ft2_render" link="func.render.html" />
      <keyword type="function" name="pango_ft2_render_layout" link="func.render_layout.html" />
      <keyword type="function" name="pango_ft2_render_layout_line" link="func.render_layout_line.html" />
      <keyword type="function" name="pango_ft2_render_layout_line_subpixel" link="func.render_layout_line_subpixel.html" since="1.6" />
      <keyword type="function" name="pango_ft2_render_layout_subpixel" link="func.render_layout_subpixel.html" since="1.6" />
      <keyword type="function" name="pango_ft2_render_transformed" link="func.render_transformed.html" since="1.6" />
      <keyword type="function" name="pango_ft2_shutdown_display" link="func.shutdown_display.html" />
   </functions>
</book>
```

As can be seen, there are no anchors in the links attribute, and thus the `linkParts` array is only 1 element long.
I don't know the internals of libhover, so I can't say if the correct fix would be to replace [ParseDevHelp.java:505](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/9982cc85ca5b46aadb3da90b35b1973e65b2f788/libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/ParseDevHelp.java#L505) with `funcMap.put(linkParts.length > 1 ? linkParts[1] : nameValue, nameValue);` or if that would cause other problems.

**Comment by jjohnstn** [comment]
The fix you propose would not work because the HTMLSaxParser in the file is not prepared for the format of html files for the pango FT2 docs.  I have looked at them.  Anyway, the short-term solution is to bail if the anchors are missing.  The long-term solution needs to add an additional parser for the newer format html files.  I have posted a PR for this #42
